=== SonamJain1/xml_validation/old/conf/evolved-intelligence-pmd-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns="http://www.evolved-intelligence.com/pmd/version2"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                targetNamespace="http://www.evolved-intelligence.com/pmd/version2"
                attributeFormDefault="unqualified"
                elementFormDefault="qualified">

    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>

    <xsd:annotation>
        <xsd:documentation><![CDATA[
    Evolved Intelligence PMD Schema, version 2.0
    Author: Dave Williams
        ]]></xsd:documentation>
    </xsd:annotation>

    <!-- ===================================================
         == Top level doc definition                      ==
         =================================================== -->
    <xsd:element name="pmd"  type="pmdType"/>

    <!-- ===================================================
         == PMD type                                      ==
         =================================================== -->
    <xsd:complexType name="pmdType">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="settings"          type="globalSettingsType"/>
                <xsd:element name="globalsettings"    type="globalSettingsType"/>
                <xsd:element name="globalSettings"    type="globalSettingsType"/>
                <xsd:element name="group"             type="groupType"/>
                <xsd:element name="grp"               type="groupType"/>
                <xsd:element name="process"           type="processType"/>
                <xsd:element name="proc"              type="processType"/>
                <xsd:element name="environment"       type="envType"/>
                <xsd:element name="env"               type="envType"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == Global Settings type                          ==
         =================================================== -->
    <xsd:complexType name="globalSettingsType">
        <xsd:sequence>
            <xsd:element name="variables"             type="variablesType"       minOccurs="0" maxOccurs="unbounded"/>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="extensionconfigdir"    type="extensionCfgDirType"/>
                <xsd:element name="extensiondir"          type="extensionCfgDirType"/>
            </xsd:choice>
            <xsd:element name="variables"             type="variablesType"       minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="consoleoutputdir"        type="xsd:string"/>

        <xsd:attribute name="snmpname"                                      type="xsd:string"/>
        <xsd:attribute name="snmpName"                                      type="xsd:string"/>
        <xsd:attribute name="SNMPName"                                      type="xsd:string"/>
        <xsd:attribute name="snmphost"                                      type="xsd:string"/>
        <xsd:attribute name="snmpHost"                                      type="xsd:string"/>
        <xsd:attribute name="SNMPHost"                                      type="xsd:string"/>
        <xsd:attribute name="snmpcommunity"                                 type="xsd:string"/>
        <xsd:attribute name="snmpCommunity"                                 type="xsd:string"/>
        <xsd:attribute name="SNMPCommunity"                                 type="xsd:string"/>
        <xsd:attribute name="snmpincludeseverityvarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="snmpIncludeSeverityVarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="SNMPIncludeSeverityVarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="snmpincludenonstandardcommentvarbind"          type="xsd:boolean"/>
        <xsd:attribute name="snmpIncludeNonStandardCommentVarbind"          type="xsd:boolean"/>
        <xsd:attribute name="SNMPIncludeNonStandardCommentVarbind"          type="xsd:boolean"/>
        <xsd:attribute name="snmpgeneratetrapsoncontrolledprocessshutdown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateTrapsOnControlledProcessShutdown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateTrapsOnControlledProcessShutDown"  type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateTrapsOnControlledProcessShutdown"  type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateTrapsOnControlledProcessShutDown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpgenerateprocessfailurecleartraps"          type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateProcessFailureClearTraps"          type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateProcessFailureClearTraps"          type="xsd:boolean"/>
        <!-- New for SNMP v3 -->
        <!-- snmpVersion defaults to v2 -->
        <xsd:attribute name="snmpVersion"             type="xsd:integer"/>
        <xsd:attribute name="snmpSecurityName"        type="xsd:string"/>
        <!-- 1 = NOAUTH_NOPRIV, 2 = AUTH_NOPRIV, 3 = AUTH_PRIV -->
        <xsd:attribute name="snmpSecurityLevel"       type="xsd:string"/>
        <!-- NONE, SHA or MD5, defaults to SHA -->
        <xsd:attribute name="snmpAuthProtocol"        type="xsd:string"/>
        <!-- NONE, DES, 3DESEDE, IDEA, AES128, AES192 or AES256, defaults to AES256 -->
        <xsd:attribute name="snmpPrivProtocol"        type="xsd:string"/>
        <xsd:attribute name="snmpAuthPassword"        type="xsd:string"/>
        <xsd:attribute name="snmpPrivPassword"        type="xsd:string"/>

        <!-- Hex - eg. 800002b804616263 - 616263 - "ABC" -->
        <xsd:attribute name="snmpEngineId"            type="xsd:string"/>
        <!-- ASCII - eg. pmd_at_host -->
        <xsd:attribute name="snmpContextName"         type="xsd:string"/>
        <!-- Hex - eg. 800002b804646566 -->
        <xsd:attribute name="snmpEngineContextId"     type="xsd:string"/>
    
        <xsd:attribute name="allowundefinedvariables" type="xsd:boolean"/>
        <xsd:attribute name="allowundefinedvars"      type="xsd:boolean"/>
    </xsd:complexType>

    <!-- ===================================================
         == Variables type                                ==
         =================================================== -->
    <xsd:complexType name="variablesType">
        <xsd:sequence>
            <xsd:element name="var"          type="varType"       minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == Var type                                      ==
         =================================================== -->
    <xsd:complexType name="varType">
        <!-- no use="required" so we allow options -->
        <!-- The following three attributes are modelled as
           - a choice in the code.
          -->
        <xsd:attribute name="name"    type="xsd:string"/>
        <xsd:attribute name="id"      type="xsd:string"/>
        <xsd:attribute name="var"     type="xsd:string"/>

        <!-- The following two attributes are modelled as
           - a choice in the code.
          -->
        <xsd:attribute name="val"     type="xsd:string"/>
        <xsd:attribute name="value"   type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == extensionCfgDir type                          ==
         =================================================== -->
    <xsd:complexType name="extensionCfgDirType">
        <xsd:sequence>
            <xsd:element name="excludedfile" type="excludedFileType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <!-- no use="required" so we can support options. -->
        <xsd:attribute name="val"      type="xsd:string"/>
        <xsd:attribute name="dir"      type="xsd:string"/>
        <xsd:attribute name="name"     type="xsd:string"/>
        <xsd:attribute name="dirname"  type="xsd:string"/>
        <xsd:attribute name="path"     type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == excludedFile type                             ==
         =================================================== -->
    <xsd:complexType name="excludedFileType">
        <!-- no use="required" so we can support options. -->
        <xsd:attribute name="val" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="file" type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == common grp and proc attributes                ==
         =================================================== -->
    <xsd:attributeGroup name="commonGrpAndProcAttribs">
        <xsd:attribute name="cwd"                       type="xsd:string"/>
        <xsd:attribute name="dir"                       type="xsd:string"/>
        <xsd:attribute name="directory"                 type="xsd:string"/>

        <xsd:attribute name="importSystemEnvironment"   type="xsd:boolean"/>
        <xsd:attribute name="importsystemenvironment"   type="xsd:boolean"/>
        <xsd:attribute name="importSystemEnv"           type="xsd:boolean"/>
        <xsd:attribute name="importsystemenv"           type="xsd:boolean"/>
        <xsd:attribute name="importSysEnv"              type="xsd:boolean"/>
        <xsd:attribute name="importsysenv"              type="xsd:boolean"/>

        <xsd:attribute name="importSystemPath"          type="xsd:boolean"/>
        <xsd:attribute name="importsystempath"          type="xsd:boolean"/>
        <xsd:attribute name="importSysPath"             type="xsd:boolean"/>
        <xsd:attribute name="importsyspath"             type="xsd:boolean"/>

        <xsd:attribute name="path"                      type="xsd:string"/>

        <xsd:attribute name="environment"               type="xsd:string"/>
        <xsd:attribute name="environ"                   type="xsd:string"/>
        <xsd:attribute name="env"                       type="xsd:string"/>

        <xsd:attribute name="initialState"              type="iStateValType"/>
        <xsd:attribute name="initialstate"              type="iStateValType"/>
        <xsd:attribute name="istate"                    type="iStateValType"/>
        <xsd:attribute name="i-state"                   type="iStateValType"/>
    </xsd:attributeGroup>

    <!-- ===================================================
         == group type                                    ==
         =================================================== -->
    <xsd:complexType name="groupType">
        <xsd:sequence>
            <xsd:element name="processes"   type="processesType"   minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name"                      type="xsd:string" use="required"/>
        <xsd:attribute name="lockstep"                  type="xsd:boolean"/>
        <xsd:attribute name="lockStep"                  type="xsd:boolean"/>
        <xsd:attribute name="active"                    type="xsd:boolean"/>

        <xsd:attributeGroup ref="commonGrpAndProcAttribs"/>
    </xsd:complexType>

    <!-- ===================================================
         == processes type                                ==
         =================================================== -->
    <xsd:complexType name="processesType">
        <xsd:sequence>
            <xsd:element name="process" type="processRefType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == processRef type                               ==
         =================================================== -->
    <xsd:complexType name="processRefType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- ===================================================
         == process type                                  ==
         =================================================== -->
    <xsd:complexType name="processType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:choice>
                <!-- environment inlined in process definition -->
                <xsd:element name="enventry"         type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="envEntry"         type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="environmentEntry" type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="environmententry" type="varType" minOccurs="0" maxOccurs="unbounded"/>

                <!-- Process arguments -->
                <xsd:element name="args"             type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="arg"              type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="individualarg"    type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="individual-arg"   type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="singlearg"        type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="single-arg"       type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>

                <!-- Stop policy -->
                <xsd:element name="stoppolicy"       type="stoppolicyType" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="stopPolicy"       type="stoppolicyType" minOccurs="0" maxOccurs="1"/>
            </xsd:choice>
        </xsd:sequence>

        <xsd:attribute name="name"                      type="xsd:string" use="required"/>
        <xsd:attribute name="cmd"                       type="xsd:string" use="required"/>

        <xsd:attribute name="stoppolicy"                type="xsd:string"/>
        <xsd:attribute name="startdelay"                type="xsd:string"/>
        <xsd:attribute name="maxstartattempts"          type="xsd:integer"/>
        <xsd:attribute name="priority"                  type="xsd:integer"/>

        <xsd:attributeGroup ref="commonGrpAndProcAttribs"/>

    </xsd:complexType>

    <!-- ===================================================
         == Stop Policy Type                              ==
         =================================================== -->
    <xsd:complexType name="stoppolicyType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <!-- Policy arguments -->
            <xsd:element name="args"             type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="arg"              type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="individualarg"    type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="individual-arg"   type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="singlearg"        type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="single-arg"       type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>

        <xsd:attribute name="name"               type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- ===================================================
         == iStateVal type                                ==
         =================================================== -->
    <xsd:simpleType name="iStateValType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="STARTED"/>
            <xsd:enumeration value="STOPPED"/>
            <xsd:enumeration value="started"/>
            <xsd:enumeration value="stopped"/>
            <xsd:enumeration value="Started"/>
            <xsd:enumeration value="Stopped"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- ===================================================securityName
         == environment type                              ==
         =================================================== -->
    <xsd:complexType name="envType">
        <xsd:sequence>
            <!-- minOccurs 0 to allow empty environment -->
            <xsd:element name="entry" type="varType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name"     type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== SonamJain1/xml_validation/new/examples/diamsfwpmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="DIAM_SFW_BASE"   val="/opt/pmon-diametersfw" />
            <var name="PMON_GRP_NAME"   val="diamsfwpmon" />
            <var name="PMON_PROC_NAME"  val="diamsfwpmon" />
        </variables>
    </settings>

    <group name="${PMON_GRP_NAME}">
        <processes>
            <process name="${PMON_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${PMON_PROC_NAME}"
             path="${DIAM_SFW_BASE}/bin"
             dir="${DIAM_SFW_BASE}/bin"
             cmd="./pmon_diamsfw">

        <args>${DIAM_SFW_BASE}/conf/pmon_diamsfw.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <!-- <envEntry var="DB_MAXLOGSIZE" val="60MB"/> -->
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${DIAM_SFW_BASE}/logs/pmon.log"/>
        <envEntry var="SLOG_pmon" val="${DIAM_SFW_BASE}/stats/pmon_stats.log"/>
        <envEntry var="DCFG_pmon" val="${DIAM_SFW_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/schema2_examples/pmd-s2-noscript-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <!-- <settings snmphost="localhost"> -->
    <settings>
        <!--
        <extensionconfigdir dir="/opt/engine/conf/pmd.d">
            <excludedfile val="ld.xml"/>
        </extensionconfigdir>
        -->
    </settings>

    <group name="ss7" lockstep="true" active="true">
        <processes>
            <process name="m3ua_0"/>
            <process name="sccp_0"/>
            <process name="isup_0"/>
            <process name="sif"/>
            <process name="mgmt"/>
            <process name="securityapp"/>
        </processes>
    </group>

    <process name="m3ua_0"  cmd="m3uaStack">
        <args>-d255 -f/opt/NGNTdapi/Logs/m3ua_0.log -maint maint:127.0.0.1:4000 -user tcap_0::3020</args>
        <args>-appId m3ua_0 -security security:127.0.0.1:9100 -loadshareCyclic</args>
        <args>-allwaysNotifyDestStatus -aspIdOfs+2 -aliasPointCode 196866 -ASPUpAckWithNoId</args>
    </process>

    <process name="sccp_0"  cmd="sccpStack">
        <args>-d0 -f/opt/NGNTdapi/Logs/tcap_0.log -telnetport 7654 -p ITU -xudt</args>
        <args>-mtpl3 etsi_mtpl3_0:127.0.0.1:3020 -user ::3090 -appId tcap_0</args>
        <args>-ui_encode -no_opId -noTdapiMod -selectEntityOnSSN -lastDestOnGt</args>
        <args>-segmentBytes 0 -security :127.0.0.1:9100 -logsize 10485760 -logcount 10</args>
    </process>

    <process name="isup_0"  cmd="isupStack" istate="STOPPED">
        <args>-f /opt/NGNTdapi/Logs/isup_0.log -d0 -apiversion 1 -allow_all_digits -idle -protocol ETSI</args>
        <args>-appId isup_0 -mnt :127.0.0.1:4000 -mtp :127.0.0.1:3020 -callctrl ::3030</args>
        <args>-sclient :127.0.0.1:9100</args>
    </process>

    <process name="sif"   cmd="sif">
        <args>/opt/engine/conf/sif.cfg</args>

        <envEntry var="DLVL_sif" val="0"/>
        <envEntry var="DLOG_sif" val="/opt/engine/logs/sif.log"/>
    </process>

    <process name="mgmt"  cmd="mgmt-daemon">
        <args>-a 62777 /opt/engine/conf/mgmt_daemon.cfg</args>

        <envEntry var="DLVL_mgmt_daemon" val="0"/>
        <envEntry var="DLOG_mgmt_daemon" val="/opt/engine/logs/mgmt_daemon.log"/>
    </process>

    <process name="securityapp" cmd="security">
        <args>/opt/engine/conf/security.cfg</args>

        <envEntry var="DLOG_security" val="/opt/engine/logs/security.log"/>
        <envEntry var="DLVL_security" val="0"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/old/conf/pmd.d/sccpandsctpwatchdogpmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="SCCPWATCHDOG_BASE" val="/opt/pmon_watchdog" />
            <!-- The watchdog pmon must run in the same, lockstep,
               - group as the Telesoft relay stack.  -->
            <var name="PMON_GRP_NAME"     val="ss7" />
            <var name="PMON_PROC_NAME"    val="sccpandsctpwatchdogpmon" />
        </variables>
    </settings>

    <group name="${PMON_GRP_NAME}" lockstep="true">
        <processes>
            <process name="${PMON_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${PMON_PROC_NAME}"
             path="${SCCPWATCHDOG_BASE}/bin"
             dir="${SCCPWATCHDOG_BASE}/bin"
             cmd="./pmon_watchdog">

        <args>${SCCPWATCHDOG_BASE}/conf/pmon_sccpandsctpwatchdog.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${SCCPWATCHDOG_BASE}/logs/pmon.log"/>
        <envEntry var="SLOG_pmon" val="${SCCPWATCHDOG_BASE}/stats/pmon_stats.log"/>
        <envEntry var="DCFG_pmon" val="${SCCPWATCHDOG_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/pmd.d/napawatch.xml
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <!-- FIXME -->
            <var name="NW_BASE" val="/opt/engine"/>
        </variables>
    </settings>

    <group name="gtp" lockstep="true">
        <processes>
            <process name="napawatch"/>
        </processes>
    </group>

    <process name="napawatch"
             cmd="./napawatch"
             directory="${NW_BASE}/bin/">

        <args>../conf/napawatch.cfg</args>

        <envEntry var="DLVL_napawatch" val="0"/>
        <envEntry var="DLOG_napawatch" val="${NW_BASE}/logs/napawatch.log"/>
        <envEntry var="LD_LIBRARY_PATH" val="/opt/napatech3/lib:${NW_BASE}/lib64"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/pmd.d/diamloctrackpmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="LOCTRACK_BASE"   val="/opt/pmon_diamloctrack" />
            <var name="PMON_GRP_NAME"   val="diamloctrackpmon" />
            <var name="PMON_PROC_NAME"  val="diamloctrackpmon" />
        </variables>
    </settings>

    <group name="${PMON_GRP_NAME}">
        <processes>
            <process name="${PMON_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${PMON_PROC_NAME}"
             path="${LOCTRACK_BASE}/bin"
             dir="${LOCTRACK_BASE}/bin"
             cmd="./pmon_diamloctrack">

        <args>${LOCTRACK_BASE}/conf/pmon_diamloctrack.cfg</args>

        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <!-- <envEntry var="DB_MAXLOGSIZE" val="60MB"/> -->
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${LOCTRACK_BASE}/logs/pmon.log"/>
        <envEntry var="DCFG_pmon" val="${LOCTRACK_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/new/examples/pmd.d/diameterfw-dif.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">

    <settings>
        <variables>
            <var name="DIF_BASE" val="/opt/engine" />
            <!-- The DIF has to be in the same process group as the diameter watchdog passive monitor -->
            <var name="DIF_GRP_NAME"      val="diameter" />
            <var name="DIF_PROC_NAME"     val="dif" />
        </variables>
    </settings>

    <group name="${DIF_GRP_NAME}">
        <processes>
            <process name="${DIF_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${DIF_PROC_NAME}"
             path="${DIF_BASE}/bin"
             dir="${DIF_BASE}/bin"
             cmd="./start-diameterfw-dif.sh">
        <envEntry var="DIF_JAVA_XMS_ARG"      val="1024m"/>
        <envEntry var="DIF_JAVA_XMX_ARG"      val="1024m"/>
        <envEntry var="DIF_BASE_DIR"          val="${DIF_BASE}"/>
        <envEntry var="DIF_TECH_ID"           val="diameterfw"/>
        <envEntry var="DIF_NODE_ID"           val="app01"/>
        <envEntry var="DIF_INSTANCE_ID"       val="01"/>
        <envEntry var="DIF_STACK_CONFIG_FILE" val="${DIF_BASE}/conf/diameter-stack-sctp-config.json"/>
        <envEntry var="DIF_STACK_APPLICATION_CONFIG_FILE" val="${DIF_BASE}/conf/diameter-stack-application-config.json"/>
        <envEntry var="DIF_TRUSTSTORE_PATH"    val="${JAVA8_HOME}/jre/lib/security/cacerts"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/old/conf/wsmspmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="WSMSPMON_BASE" val="/opt/pmon-wsms"/>
        </variables>
    </settings>

    <group name="wsmspmon">
        <processes>
            <process name="wsmspmon"/>
        </processes>
    </group>

    <process name="wsmspmon"
             path="${WSMSPMON_BASE}/bin"
             dir="${WSMSPMON_BASE}/bin"
             cmd="./pmon_wsms">

        <args>${WSMSPMON_BASE}/conf/pmon_wsms.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${WSMSPMON_BASE}/logs/pmon.log"/>
        <envEntry var="DCFG_pmon" val="${WSMSPMON_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/pmd.d/ss7.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <group name="ss7" importSystemEnvironment="true" lockstep="true">
        <processes>
            <process name="m3ua_0"/>
            <process name="sccp_0"/>
            <process name="sif"/>
            <process name="mgmt"/>
        </processes>
    </group>

    <process name="m3ua_0" cmd="/opt/engine/bin/m3uaStack0.sh" />
    <process name="sccp_0" cmd="/opt/engine/bin/sccpStack0.sh" />
    <process name="sif"    cmd="/opt/engine/bin/sif.sh" />
    <process name="mgmt"   cmd="/opt/engine/bin/mgmt-daemon.sh" />

</pmd>
