=== SonamJain1/xml_validation/old/conf/evolved-intelligence-pmd-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns="http://www.evolved-intelligence.com/pmd/version2"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                targetNamespace="http://www.evolved-intelligence.com/pmd/version2"
                attributeFormDefault="unqualified"
                elementFormDefault="qualified">

    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>

    <xsd:annotation>
        <xsd:documentation><![CDATA[
    Evolved Intelligence PMD Schema, version 2.0
    Author: Dave Williams
        ]]></xsd:documentation>
    </xsd:annotation>

    <!-- ===================================================
         == Top level doc definition                      ==
         =================================================== -->
    <xsd:element name="pmd"  type="pmdType"/>

    <!-- ===================================================
         == PMD type                                      ==
         =================================================== -->
    <xsd:complexType name="pmdType">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="settings"          type="globalSettingsType"/>
                <xsd:element name="globalsettings"    type="globalSettingsType"/>
                <xsd:element name="globalSettings"    type="globalSettingsType"/>
                <xsd:element name="group"             type="groupType"/>
                <xsd:element name="grp"               type="groupType"/>
                <xsd:element name="process"           type="processType"/>
                <xsd:element name="proc"              type="processType"/>
                <xsd:element name="environment"       type="envType"/>
                <xsd:element name="env"               type="envType"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == Global Settings type                          ==
         =================================================== -->
    <xsd:complexType name="globalSettingsType">
        <xsd:sequence>
            <xsd:element name="variables"             type="variablesType"       minOccurs="0" maxOccurs="unbounded"/>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="extensionconfigdir"    type="extensionCfgDirType"/>
                <xsd:element name="extensiondir"          type="extensionCfgDirType"/>
            </xsd:choice>
            <xsd:element name="variables"             type="variablesType"       minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="consoleoutputdir"        type="xsd:string"/>

        <xsd:attribute name="snmpname"                                      type="xsd:string"/>
        <xsd:attribute name="snmpName"                                      type="xsd:string"/>
        <xsd:attribute name="SNMPName"                                      type="xsd:string"/>
        <xsd:attribute name="snmphost"                                      type="xsd:string"/>
        <xsd:attribute name="snmpHost"                                      type="xsd:string"/>
        <xsd:attribute name="SNMPHost"                                      type="xsd:string"/>
        <xsd:attribute name="snmpcommunity"                                 type="xsd:string"/>
        <xsd:attribute name="snmpCommunity"                                 type="xsd:string"/>
        <xsd:attribute name="SNMPCommunity"                                 type="xsd:string"/>
        <xsd:attribute name="snmpincludeseverityvarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="snmpIncludeSeverityVarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="SNMPIncludeSeverityVarbind"                    type="xsd:boolean"/>
        <xsd:attribute name="snmpincludenonstandardcommentvarbind"          type="xsd:boolean"/>
        <xsd:attribute name="snmpIncludeNonStandardCommentVarbind"          type="xsd:boolean"/>
        <xsd:attribute name="SNMPIncludeNonStandardCommentVarbind"          type="xsd:boolean"/>
        <xsd:attribute name="snmpgeneratetrapsoncontrolledprocessshutdown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateTrapsOnControlledProcessShutdown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateTrapsOnControlledProcessShutDown"  type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateTrapsOnControlledProcessShutdown"  type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateTrapsOnControlledProcessShutDown"  type="xsd:boolean"/>
        <xsd:attribute name="snmpgenerateprocessfailurecleartraps"          type="xsd:boolean"/>
        <xsd:attribute name="snmpGenerateProcessFailureClearTraps"          type="xsd:boolean"/>
        <xsd:attribute name="SNMPGenerateProcessFailureClearTraps"          type="xsd:boolean"/>
        <!-- New for SNMP v3 -->
        <!-- snmpVersion defaults to v2 -->
        <xsd:attribute name="snmpVersion"             type="xsd:integer"/>
        <xsd:attribute name="snmpSecurityName"        type="xsd:string"/>
        <!-- 1 = NOAUTH_NOPRIV, 2 = AUTH_NOPRIV, 3 = AUTH_PRIV -->
        <xsd:attribute name="snmpSecurityLevel"       type="xsd:string"/>
        <!-- NONE, SHA or MD5, defaults to SHA -->
        <xsd:attribute name="snmpAuthProtocol"        type="xsd:string"/>
        <!-- NONE, DES, 3DESEDE, IDEA, AES128, AES192 or AES256, defaults to AES256 -->
        <xsd:attribute name="snmpPrivProtocol"        type="xsd:string"/>
        <xsd:attribute name="snmpAuthPassword"        type="xsd:string"/>
        <xsd:attribute name="snmpPrivPassword"        type="xsd:string"/>

        <!-- Hex - eg. 800002b804616263 - 616263 - "ABC" -->
        <xsd:attribute name="snmpEngineId"            type="xsd:string"/>
        <!-- ASCII - eg. pmd_at_host -->
        <xsd:attribute name="snmpContextName"         type="xsd:string"/>
        <!-- Hex - eg. 800002b804646566 -->
        <xsd:attribute name="snmpEngineContextId"     type="xsd:string"/>
    
        <xsd:attribute name="allowundefinedvariables" type="xsd:boolean"/>
        <xsd:attribute name="allowundefinedvars"      type="xsd:boolean"/>
    </xsd:complexType>

    <!-- ===================================================
         == Variables type                                ==
         =================================================== -->
    <xsd:complexType name="variablesType">
        <xsd:sequence>
            <xsd:element name="var"          type="varType"       minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == Var type                                      ==
         =================================================== -->
    <xsd:complexType name="varType">
        <!-- no use="required" so we allow options -->
        <!-- The following three attributes are modelled as
           - a choice in the code.
          -->
        <xsd:attribute name="name"    type="xsd:string"/>
        <xsd:attribute name="id"      type="xsd:string"/>
        <xsd:attribute name="var"     type="xsd:string"/>

        <!-- The following two attributes are modelled as
           - a choice in the code.
          -->
        <xsd:attribute name="val"     type="xsd:string"/>
        <xsd:attribute name="value"   type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == extensionCfgDir type                          ==
         =================================================== -->
    <xsd:complexType name="extensionCfgDirType">
        <xsd:sequence>
            <xsd:element name="excludedfile" type="excludedFileType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <!-- no use="required" so we can support options. -->
        <xsd:attribute name="val"      type="xsd:string"/>
        <xsd:attribute name="dir"      type="xsd:string"/>
        <xsd:attribute name="name"     type="xsd:string"/>
        <xsd:attribute name="dirname"  type="xsd:string"/>
        <xsd:attribute name="path"     type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == excludedFile type                             ==
         =================================================== -->
    <xsd:complexType name="excludedFileType">
        <!-- no use="required" so we can support options. -->
        <xsd:attribute name="val" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="file" type="xsd:string"/>
    </xsd:complexType>

    <!-- ===================================================
         == common grp and proc attributes                ==
         =================================================== -->
    <xsd:attributeGroup name="commonGrpAndProcAttribs">
        <xsd:attribute name="cwd"                       type="xsd:string"/>
        <xsd:attribute name="dir"                       type="xsd:string"/>
        <xsd:attribute name="directory"                 type="xsd:string"/>

        <xsd:attribute name="importSystemEnvironment"   type="xsd:boolean"/>
        <xsd:attribute name="importsystemenvironment"   type="xsd:boolean"/>
        <xsd:attribute name="importSystemEnv"           type="xsd:boolean"/>
        <xsd:attribute name="importsystemenv"           type="xsd:boolean"/>
        <xsd:attribute name="importSysEnv"              type="xsd:boolean"/>
        <xsd:attribute name="importsysenv"              type="xsd:boolean"/>

        <xsd:attribute name="importSystemPath"          type="xsd:boolean"/>
        <xsd:attribute name="importsystempath"          type="xsd:boolean"/>
        <xsd:attribute name="importSysPath"             type="xsd:boolean"/>
        <xsd:attribute name="importsyspath"             type="xsd:boolean"/>

        <xsd:attribute name="path"                      type="xsd:string"/>

        <xsd:attribute name="environment"               type="xsd:string"/>
        <xsd:attribute name="environ"                   type="xsd:string"/>
        <xsd:attribute name="env"                       type="xsd:string"/>

        <xsd:attribute name="initialState"              type="iStateValType"/>
        <xsd:attribute name="initialstate"              type="iStateValType"/>
        <xsd:attribute name="istate"                    type="iStateValType"/>
        <xsd:attribute name="i-state"                   type="iStateValType"/>
    </xsd:attributeGroup>

    <!-- ===================================================
         == group type                                    ==
         =================================================== -->
    <xsd:complexType name="groupType">
        <xsd:sequence>
            <xsd:element name="processes"   type="processesType"   minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name"                      type="xsd:string" use="required"/>
        <xsd:attribute name="lockstep"                  type="xsd:boolean"/>
        <xsd:attribute name="lockStep"                  type="xsd:boolean"/>
        <xsd:attribute name="active"                    type="xsd:boolean"/>

        <xsd:attributeGroup ref="commonGrpAndProcAttribs"/>
    </xsd:complexType>

    <!-- ===================================================
         == processes type                                ==
         =================================================== -->
    <xsd:complexType name="processesType">
        <xsd:sequence>
            <xsd:element name="process" type="processRefType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- ===================================================
         == processRef type                               ==
         =================================================== -->
    <xsd:complexType name="processRefType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- ===================================================
         == process type                                  ==
         =================================================== -->
    <xsd:complexType name="processType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:choice>
                <!-- environment inlined in process definition -->
                <xsd:element name="enventry"         type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="envEntry"         type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="environmentEntry" type="varType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="environmententry" type="varType" minOccurs="0" maxOccurs="unbounded"/>

                <!-- Process arguments -->
                <xsd:element name="args"             type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="arg"              type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="individualarg"    type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="individual-arg"   type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="singlearg"        type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="single-arg"       type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>

                <!-- Stop policy -->
                <xsd:element name="stoppolicy"       type="stoppolicyType" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="stopPolicy"       type="stoppolicyType" minOccurs="0" maxOccurs="1"/>
            </xsd:choice>
        </xsd:sequence>

        <xsd:attribute name="name"                      type="xsd:string" use="required"/>
        <xsd:attribute name="cmd"                       type="xsd:string" use="required"/>

        <xsd:attribute name="stoppolicy"                type="xsd:string"/>
        <xsd:attribute name="startdelay"                type="xsd:string"/>
        <xsd:attribute name="maxstartattempts"          type="xsd:integer"/>
        <xsd:attribute name="priority"                  type="xsd:integer"/>

        <xsd:attributeGroup ref="commonGrpAndProcAttribs"/>

    </xsd:complexType>

    <!-- ===================================================
         == Stop Policy Type                              ==
         =================================================== -->
    <xsd:complexType name="stoppolicyType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <!-- Policy arguments -->
            <xsd:element name="args"             type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="arg"              type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="individualarg"    type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="individual-arg"   type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="singlearg"        type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="single-arg"       type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>

        <xsd:attribute name="name"               type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- ===================================================
         == iStateVal type                                ==
         =================================================== -->
    <xsd:simpleType name="iStateValType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="STARTED"/>
            <xsd:enumeration value="STOPPED"/>
            <xsd:enumeration value="started"/>
            <xsd:enumeration value="stopped"/>
            <xsd:enumeration value="Started"/>
            <xsd:enumeration value="Stopped"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- ===================================================securityName
         == environment type                              ==
         =================================================== -->
    <xsd:complexType name="envType">
        <xsd:sequence>
            <!-- minOccurs 0 to allow empty environment -->
            <xsd:element name="entry" type="varType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name"     type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== SonamJain1/xml_validation/old/conf/pmd.d/vif.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">

    <settings>
        <variables>
            <var name="VIF_BASE" val="/opt/engine" />
            <!-- The VIF has to be in the same process group as the sip watchdog passive monitor -->
            <var name="VIF_GRP_NAME"      val="sip" />
            <var name="VIF_PROC_NAME"     val="vif" />
        </variables>
    </settings>

    <group name="${VIF_GRP_NAME}">
        <processes>
            <process name="${VIF_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${VIF_PROC_NAME}"
             path="${VIF_BASE}/bin"
             dir="${VIF_BASE}/bin"
             cmd="./start-vif.sh">
        <envEntry var="VIF_JAVA_XMS_ARG"      val="1024m"/>
        <envEntry var="VIF_JAVA_XMX_ARG"      val="1024m"/>
        <envEntry var="VIF_BASE_DIR"          val="${VIF_BASE}"/>
        <envEntry var="VIF_STACK_CONFIG_FILE" val="${VIF_BASE}/conf/sip-stack-config.json"/>
        <envEntry var="VIF_STACK_APPLICATION_CONFIG_FILE" val="${VIF_BASE}/conf/sip-application-config.json"/>
        <envEntry var="VIF_HEADER_CONFIG_FILE" val="${VIF_BASE}/conf/header.json"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/tcpwatchdogpmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="TCPWATCHDOGPMON_BASE" val="/opt/pmon-steering"/>
        </variables>
    </settings>

    <group name="tcpwatchdogpmon">
        <processes>
            <process name="tcpwatchdogpmon"/>
        </processes>
    </group>

    <process name="tcpwatchdogpmon" path="${TCPWATCHDOGPMON_BASE}/bin" dir="${TCPWATCHDOGPMON_BASE}/bin" cmd="./pmon_tcpwatchdog">

        <args>${TCPWATCHDOGPMON_BASE}/conf/pmon_tcpwatchdog.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${TCPWATCHDOGPMON_BASE}/logs/pmon.log"/>
        <envEntry var="DCFG_pmon" val="${TCPWATCHDOGPMON_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/pmd.d/ei-diam-watchdog.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">

    <settings>
        <variables>
            <var name="DIF_BASE" val="/opt/engine" />
            <!-- The DIF has to be in the same process group as the diameter watchdog passive monitor -->
            <var name="DIF_GRP_NAME"      val="diameter" />
            <var name="DIF_PROC_NAME"     val="tcp-diam-watchdog" />
        </variables>
    </settings>

    <group name="${DIF_GRP_NAME}">
        <processes>
            <process name="${DIF_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${DIF_PROC_NAME}"
             path="${DIF_BASE}/bin"
             dir="${DIF_BASE}/bin"
             cmd="./start-ei-diam-watchdog.sh">
        <envEntry var="DIF_JAVA_XMS_ARG"      val="32m"/>
        <envEntry var="DIF_JAVA_XMX_ARG"      val="64m"/>
        <envEntry var="EI_DIAM_WATCHDOG_CONFIG_FILE" val="/opt/engine/conf/EIDiameterStackWatchdogConfig.json"/>
    </process>
</pmd>

=== SonamJain1/xml_validation/new/examples/dist.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="DIST_BASE"       val="/opt/dist" />
            <var name="DIST_GRP_NAME"   val="dist" />
            <var name="DIST_PROC_NAME"  val="dist" />
        </variables>
    </settings>

    <group name="${DIST_GRP_NAME}">
        <processes>
            <process name="${DIST_PROC_NAME}"/>
        </processes>
    </group>

    <process name="${DIST_PROC_NAME}"
             path="${DIST_BASE}/bin"
             dir="${DIST_BASE}/bin"
             cmd="./dist">

        <args>${DIST_BASE}/conf/dist.cfg</args>

        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="0"/>
        <!-- <envEntry var="DB_MAXLOGSIZE" val="60MB"/> -->
        <envEntry var="DLVL_dist" val="0"/>
        <envEntry var="DLOG_dist" val="${DIST_BASE}/logs/dist.log"/>
        <!-- Currently we configure dist with component level debugging disabled.  -->
        <!-- <envEntry var="DCFG_dist" val="${DIST_BASE}/conf/dist_log.cfg"/> -->
    </process>

</pmd>

=== SonamJain1/xml_validation/new/examples/sorpmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="SORPMON_BASE" val="/opt/pmon-steering"/>
        </variables>
    </settings>

    <group name="sorpmon">
        <processes>
            <process name="sorpmon"/>
        </processes>
    </group>

    <process name="sorpmon"
             path="${SORPMON_BASE}/bin"
             dir="${SORPMON_BASE}/bin"
             cmd="./pmon_sorlocmgmt">

        <args>${SORPMON_BASE}/conf/pmon_sor.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${SORPMON_BASE}/logs/pmon.log"/>
        <envEntry var="DCFG_pmon" val="${SORPMON_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/new/examples/gtpif.xml
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <!-- FIXME -->
            <var name="GIF_BASE" val="/opt/engine"/>
        </variables>
    </settings>

    <group name="gtp" lockstep="true">
        <processes>
            <process name="gtpif"/>
        </processes>
    </group>

    <process name="gtpif"
             cmd="./runGIF.sh"
             directory="${GIF_BASE}/bin/">

        <args>../conf/gtpif.cfg</args>

        <envEntry var="DLVL_gtpif" val="0"/>
        <envEntry var="DLOG_gtpif" val="${GIF_BASE}/logs/gtpif.log"/>
        <envEntry var="SLOG_gtpif" val="${GIF_BASE}/stats/gtpif_stats.log"/>
        <envEntry var="LD_LIBRARY_PATH" val="/opt/napatech3/lib:${GIF_BASE}/lib64"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/new/examples/vhepmon.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">
    <!-- Need schemaLocation or entityResolver is not invoked -->

    <settings>
        <variables>
            <var name="VHE_PMON_BASE" val="/opt/pmon-vhe"/>
        </variables>
    </settings>

    <group name="vhepmon">
        <processes>
            <process name="vhepmon"/>
        </processes>
    </group>

    <process name="vhepmon"
             path="${VHE_PMON_BASE}/bin"
             dir="${VHE_PMON_BASE}/bin"
             cmd="pmon_8.5.3">

        <args>${VHE_PMON_BASE}/conf/pmon_vhe.cfg</args>

        <envEntry var="LD_BIND_NOW" val="1"/>
        <envEntry var="DB_PRINT" val="0"/>
        <envEntry var="DB_COMPDEBUG" val="1"/>
        <envEntry var="DLVL_pmon" val="0"/>
        <envEntry var="DLOG_pmon" val="${VHE_PMON_BASE}/logs/pmon.log"/>
        <envEntry var="DCFG_pmon" val="${VHE_PMON_BASE}/conf/pmon_log.cfg"/>
    </process>

</pmd>

=== SonamJain1/xml_validation/output/pmd.d/sigfirewall-diameter.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://www.evolved-intelligence.com/pmd/version2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.evolved-intelligence.com/pmd/version2 http://www.evolved-intelligence.com/pmd/schema/evolved-intelligence-pmd-v2.xsd">

    <settings>
        <variables>
            <var name="CFG_SRV_BASE" val="/opt/engine"/>
        </variables>
    </settings>


    <group name="sigfirewalldiameter">
        <processes>
            <process name="sigfirewalldiameter"/>
        </processes>
    </group>

    <process name="sigfirewalldiameter"
             path="${CFG_SRV_BASE}/bin"
             directory="${CFG_SRV_BASE}/bin"
             cmd="sigfirewalldiameter" >
        <envEntry var="SIG_FIREWALL_DIAMETER_JAVA_XMS_ARG"         val="1024m"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_JAVA_XMX_ARG"         val="1024m"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_BASE_DIR"             val="/opt/engine"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_NODE_ID"              val="app01"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_INSTANCE_ID"          val="01"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_EWOK_NODE_ID"         val="32221"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_RATE_LIMIT_HZ_PORT"   val="5712"/>
        <envEntry var="SIG_FIREWALL_DIAMETER_TRUSTSTORE_PATH"    val="${JAVA8_HOME}/jre/lib/security/cacerts"/>
    </process>

</pmd>
